### ISSUE TITLE
apply checkbox genre tags

### ISSUE THREAD

**Issue by kairo97** [kairo97/Steam-sale-tracker-repo#7]
### USER STORY
AS A gamer only interested in certain games
I WANT to filter out games I'm not interested in
SO THAT I only see games in genres that interest me
### ACCEPTANCE CRITERIA 
- [x]  a nav bar with checkboxes listing genre is on page
- [x] the checkboxes when checked filter results to only show that genre
- [x] multiple checkboxes can be applied at same time

**Comment by nguyet33** [comment]
Switch over to radio style with pricing.
